# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::788354698069:role/github-actions-role
          aws-region: ap-southeast-1
